select * from Suppliers
select * from Equipment
select * from Orders
select * from Donors
select * from Repairs
select * from EquipRepairs
select * from equip_order
select * from Vehicles
select * from VehiclesRepairs
select * from vehicle_equip
